// reads-angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'reads-angular';
}

<!--The content below is only a placeholder and can be replaced.-->
    <header class="container-fluid py-3 d-flex justify-content-center text-center bg-info text-light">
        <div class="col-sm-8 d-flex justify-content-start align-items-center">
            <i class="fas fa-3x fa-book-reader"></i>
            <h3 class="px-4">{{title}}</h3>
        </div>
    </header>
    <section class="container-fluid d-flex flex-column align-items-center">
        <nav class="d-flex justify-content-center py-5">
            <div class="col-sm-8 d-flex justify-content-center text-center">
                <div class="link mr-3" [routerLink]="['/authors']">
                    <img alt="Authors" src="http://placehold.it/200/100" />
                    <h5>Authors</h5>
                </div>
                <div class="link ml-3" [routerLink]="['/books']">
                    <img alt="Books" src="http://placehold.it/200/100" />
                    <h5>Books</h5>
                </div>
            </div>
        </nav>
        <main class="bg-info col-sm-8">

        <router-outlet></router-outlet>

        </main>
    </section>

// reads-react/src/App.js
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import NavBar from './components/NavBar'
import Authors from './components/Authors'
import Books from './components/Books'
import {Link, Router} from '@reach/router'

const baseURL = 'http://localhost:3000'
const links = ["Authors", "Books"]
class App extends Component {
    constructor(){
        super()
        this.state = {
            authors: [],
            books: [],
        }
    }
    getAuthors() {
        return fetch(`${baseURL}/authors`)
    }
    getBooks() {
        return fetch(`${baseURL}/books`)
    }

    render() {
        return (
            <div className="App">
                <main className="container-flex bg-info d-flex flex-column justify-content-between">

                    <header className="d-flex align-items-center text-light bg-dark d-flex justify-content-between px-5"> <h1> Galvanize Reads </h1> <NavBar links={links} /> </header>

                    <Router>
                        <Home path="/" />
                        <Authors getAuthors={this.getAuthors} path="/authors" />
                        <Books getBooks={this.getBooks} path="/books" />
                    </Router>

                    <footer className="bg-dark text-light"> test footer </footer>
                </main>

            </div>
            );
}
}

const Home = () => {
    return (
        <div>Welcome!</div>
    )
}

export default App;
